### ISSUE TITLE
Auth Issues

### ISSUE THREAD

**Issue by Peter-Escueta** [AIMS-Capstone/TMS-Capstone#13]
No js functionalities on all

SHOW/HIDE password not working

Carousel is still broken

Inter font is not working/loading; default font is showing

Register page: Change "Already have an account?" to "Don't have an account yet?"

**Comment by JLegrama** [comment]
For my assigned open issues, kindly see my recent pull request:
https://github.com/AIMS-Capstone/TMS-Capstone/pull/16
